apiVersion: v1
kind: ConfigMap
metadata:
  name: opendatahub-mcplifecycleoperator-config
data:
  operand-image: "quay.io/redhat-user-workloads/mcp-lifecycle-operator-tenant/mcp-lifecycle-operator-main@sha256:a9d203700dea99c847c7004c691ad4cb6347c07111f2c8045ca7a3ab77566251"
  operand-namespace: "mcp-lifecycle-operator-system"
